<a href="https://colab.research.google.com/github/hashmiusman9212/first-repo/blob/main/class_18_(panda).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel('SampleData.xlsx')

In [4]:
data

    OrderDate   Region       Rep     Item  Units  Unit Cost    Total
0  2019-01-06     East     Jones   Pencil     95       1.99   189.05
1  2019-01-23  Central    Kivell   Binder     50      19.99   999.50
2  2019-02-09  Central   Jardine   Pencil     36       4.99   179.64
3  2019-02-26  Central      Gill      Pen     27      19.99   539.73
4  2019-03-15     West   Sorvino   Pencil     56       2.99   167.44
5  2019-04-01     East     Jones   Binder     60       4.99   299.40
6  2019-04-18  Central   Andrews   Pencil     75       1.99   149.25
7  2019-05-05  Central   Jardine   Pencil     90       4.99   449.10
8  2019-05-22     West  Thompson   Pencil     32       1.99    63.68
9  2019-06-08     East     Jones   Binder     60       8.99   539.40
10 2019-06-25  Central    Morgan   Pencil     90       4.99   449.10
11 2019-07-12     East    Howard   Binder     29       1.99    57.71
12 2019-07-29     East    Parent   Binder     81      19.99  1619.19
13 2019-08-15     East     Jones   Pencil     35       4.99   174.65
14 2019-09-01  Central     Smith     Desk      2     125.00   250.00
15 2019-09-18     East     Jones  Pen Set     16      15.99   255.84
16 2019-10-05  Central    Morgan   Binder     28       8.99   251.72
17 2019-10-22     East     Jones      Pen     64       8.99   575.36
18 2019-11-08     East    Parent      Pen     15      19.99   299.85
19 2019-11-25  Central    Kivell  Pen Set     96       4.99   479.04
20 2019-12-12  Central     Smith   Pencil     67       1.29    86.43
21 2019-12-29     East    Parent  Pen Set     74      15.99  1183.26
22 2020-01-15  Central      Gill   Binder     46       8.99   413.54
23 2020-02-01  Central     Smith   Binder     87      15.00  1305.00
24 2020-02-18     East     Jones   Binder      4       4.99    19.96
25 2020-03-07     West   Sorvino   Binder      7      19.99   139.93
26 2020-03-24  Central   Jardine  Pen Set     50       4.99   249.50
27 2020-04-10  Central   Andrews   Pencil     66       1.99   131.34
28 2020-04-27     East    Howard      Pen     96       4.99   479.04
29 2020-05-14  Central      Gill   Pencil     53       1.29    68.37
30 2020-05-31  Central      Gill   Binder     80       8.99   719.20
31 2020-06-17  Central    Kivell     Desk      5     125.00   625.00
32 2020-07-04     East     Jones  Pen Set     62       4.99   309.38
33 2020-07-21  Central    Morgan  Pen Set     55      12.49   686.95
34 2020-08-07  Central    Kivell  Pen Set     42      23.95  1005.90
35 2020-08-24     West   Sorvino     Desk      3     275.00   825.00
36 2020-09-10  Central      Gill   Pencil      7       1.29     9.03
37 2020-09-27     West   Sorvino      Pen     76       1.99   151.24
38 2020-10-14     West  Thompson   Binder     57      19.99  1139.43
39 2020-10-31  Central   Andrews   Pencil     14       1.29    18.06
40 2020-11-17  Central   Jardine   Binder     11       4.99    54.89
41 2020-12-04  Central   Jardine   Binder     94      19.99  1879.06
42 2020-12-21  Central   Andrews   Binder     28       4.99   139.72

In [5]:
data.head(10)

   OrderDate   Region       Rep    Item  Units  Unit Cost   Total
0 2019-01-06     East     Jones  Pencil     95       1.99  189.05
1 2019-01-23  Central    Kivell  Binder     50      19.99  999.50
2 2019-02-09  Central   Jardine  Pencil     36       4.99  179.64
3 2019-02-26  Central      Gill     Pen     27      19.99  539.73
4 2019-03-15     West   Sorvino  Pencil     56       2.99  167.44
5 2019-04-01     East     Jones  Binder     60       4.99  299.40
6 2019-04-18  Central   Andrews  Pencil     75       1.99  149.25
7 2019-05-05  Central   Jardine  Pencil     90       4.99  449.10
8 2019-05-22     West  Thompson  Pencil     32       1.99   63.68
9 2019-06-08     East     Jones  Binder     60       8.99  539.40

In [6]:
data.tail(10)

    OrderDate   Region       Rep     Item  Units  Unit Cost    Total
33 2020-07-21  Central    Morgan  Pen Set     55      12.49   686.95
34 2020-08-07  Central    Kivell  Pen Set     42      23.95  1005.90
35 2020-08-24     West   Sorvino     Desk      3     275.00   825.00
36 2020-09-10  Central      Gill   Pencil      7       1.29     9.03
37 2020-09-27     West   Sorvino      Pen     76       1.99   151.24
38 2020-10-14     West  Thompson   Binder     57      19.99  1139.43
39 2020-10-31  Central   Andrews   Pencil     14       1.29    18.06
40 2020-11-17  Central   Jardine   Binder     11       4.99    54.89
41 2020-12-04  Central   Jardine   Binder     94      19.99  1879.06
42 2020-12-21  Central   Andrews   Binder     28       4.99   139.72

In [7]:
data.index

RangeIndex(start=0, stop=43, step=1)

In [8]:
data.columns

Index(['OrderDate', 'Region', 'Rep', 'Item', 'Units', 'Unit Cost', 'Total'], dtype='object')

In [9]:
data["Region"]

0        East
1     Central
2     Central
3     Central
4        West
5        East
6     Central
7     Central
8        West
9        East
10    Central
11       East
12       East
13       East
14    Central
15       East
16    Central
17       East
18       East
19    Central
20    Central
21       East
22    Central
23    Central
24       East
25       West
26    Central
27    Central
28       East
29    Central
30    Central
31    Central
32       East
33    Central
34    Central
35       West
36    Central
37       West
38       West
39    Central
40    Central
41    Central
42    Central
Name: Region, dtype: object

In [10]:
d_r = data['Region']
d_OB = data['OrderDate']
d_re = data['Rep']
d_I = data['Item']
d_UC = data['Unit Cost']
d_T = data['Total']
d_r

0        East
1     Central
2     Central
3     Central
4        West
5        East
6     Central
7     Central
8        West
9        East
10    Central
11       East
12       East
13       East
14    Central
15       East
16    Central
17       East
18       East
19    Central
20    Central
21       East
22    Central
23    Central
24       East
25       West
26    Central
27    Central
28       East
29    Central
30    Central
31    Central
32       East
33    Central
34    Central
35       West
36    Central
37       West
38       West
39    Central
40    Central
41    Central
42    Central
Name: Region, dtype: object

In [11]:
type(d_T
    )

pandas.core.series.Series

In [12]:
t_data = data[data['Region'] == 'East']

In [14]:
for i in items:
    d_var = data[data['Item'] == i]
    d_var.to_excel(i+'_data.xlsx')

NameError: ignored